runtime: php55

handlers:
- url: /assets/css
  static_dir: assets/css

- url: /fonts
  static_dir: assets/fonts

- url: /assets/fonts
  static_dir: assets/fonts

- url: /assets/js
  static_dir: assets/js

- url: /assets/media
  static_dir: assets/media
  
- url: /assets/img/(.*\.(gif|png|jpg))
  static_files: assets/img/\1
  upload: assets/img/(.*\.(gif|png|jpg))

- url: /assets/media/(.*\.(gif|png|jpg))
  static_files: assets/media/\1
  upload: assets/media/(.*\.(gif|png|jpg))
  
- url: /
  script: index.php

- url: /index.*
  script: index.php

- url: /pages/news.*
  script: pages/news.php

- url: /pages/profile.*
  script: pages/profile.php

- url: /pages/about.*
  script: pages/about.php

- url: /pages/album.*
  script: pages/album.php

- url: /pages/concert.*
  script: pages/concert.php

- url: /pages/dancepratice.*
  script: pages/dancepratice.php

- url: /pages/liveshow.*
  script: pages/liveshow.php

- url: /pages/musicvideo.*
  script: pages/musicvideo.php

- url: /pages/news_content.*
  script: pages/news_content.php

- url: /pages/picture.*
  script: pages/picture.php

- url: /pages/schedule.*
  script: pages/schedule.php

- url: /news.*
  script: pages/news.php

- url: /profile.*
  script: pages/profile.php

- url: /about.*
  script: pages/about.php

- url: /album.*
  script: pages/album.php

- url: /concert.*
  script: pages/concert.php

- url: /dancepratice.*
  script: pages/dancepratice.php

- url: /liveshow.*
  script: pages/liveshow.php

- url: /musicvideo.*
  script: pages/musicvideo.php

- url: /news_content.*
  script: pages/news_content.php

- url: /picture.*
  script: pages/picture.php

- url: /schedule.*
  script: pages/schedule.php


