runtime: php55

handlers:
- url: /assets/css
  static_dir: assets/css

- url: /assets/fonts
  static_dir: assets/fonts

- url: /assets/js
  static_dir: assets/js

- url: /assets/media
  static_dir: assets/media
  
- url: /assets/img/(.*\.(gif|png|jpg))
  static_files: assets/img/\1
  upload: assets/img/(.*\.(gif|png|jpg))
  
- url: /.*
  script: index.php

- url: /pages/news
  script: pages/news.php

- url: /pages/news
  script: pages/news.php